# Generated by Django 2.1.5 on 2020-06-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('userID', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
