# Generated by Django 2.1.5 on 2020-06-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bootapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='userID',
            new_name='user_id',
        ),
    ]
